name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check tag is on main
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
          if ! git rev-list origin/main | grep -q "$TAG_COMMIT"; then
            echo "❌ Tag is not from main branch"
            exit 1
          fi

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

  build:
    needs: check
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: "0"
      VERSION: ${{ github.ref_name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: windows, goarch: amd64,           os: ubuntu-latest , artifact: windows_amd64 }
          - { goos: windows, goarch: arm64,           os: ubuntu-latest , artifact: windows_arm64 }
          - { goos: windows, goarch: "386",           os: ubuntu-latest , artifact: windows_x86 }
          - { goos: darwin,  goarch: arm64,           os: macos-latest  , artifact: darwin_aarch64 }
          - { goos: darwin,  goarch: amd64,           os: macos-latest  , artifact: darwin_x64 }
          - { goos: linux,   goarch: amd64,           os: ubuntu-latest , artifact: linux_amd64 }
          - { goos: linux,   goarch: arm64,           os: ubuntu-latest , artifact: linux_arm64 }
          - { goos: linux,   goarch: "386",           os: ubuntu-latest , artifact: linux_x86 }
          - { goos: linux,   goarch: arm,   arm: "5", os: ubuntu-latest , artifact: linux_arm5 }
          - { goos: linux,   goarch: arm,   arm: "6", os: ubuntu-latest , artifact: linux_arm6 }
          - { goos: linux,   goarch: arm,   arm: "7", os: ubuntu-latest , artifact: linux_arm7 }

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: mkdir -p build

      - if: ${{ matrix.goos != 'linux' }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make release
      - if: ${{ matrix.goos == 'linux' && matrix.goarch != 'arm' }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make release
      - if: ${{ matrix.goos == 'linux' && matrix.goarch == 'arm' }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.arm }} make release-arm

      - uses: actions/upload-artifact@v6
        with:
          name: build-${{ matrix.artifact }}
          path: build/msr-downloader-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repository

      - name: Fetch update logs
        id: fetch_update_logs
        run: bash ./scripts/extract_update_logs.sh
        shell: bash

      - name: Set Environment
        run: echo "BUILD_TIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV

      - run: |
          if [ -z "${UPDATE_LOGS}" ]; then
            echo "No update logs found, using default message."
            UPDATE_LOGS="More new features are now supported. Check for detailed changelog soon."
          else
            echo "Using found update logs."
          fi
          
          cat > release.txt << EOF
          ${UPDATE_LOGS}
          
          Created at ${{ env.BUILD_TIME }}.
          EOF

      - uses: actions/download-artifact@v7
        with:
          path: build
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          body_path: release.txt
          files: build/msr-downloader-*
          prerelease: ${{ contains(github.ref_name, '-rc') }}

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: build-*
